import Head from "next/head";
import Card from "@/components/card";
import { MyContext } from "@/context/MyContext";
import { useContext } from "react";

export default function Home() {
  const { posts } = useContext(MyContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-[90vh]">
        {posts.map((post) => (
          <Card post={post} key={post.id} />
        ))}
      </div>
    </>
  );
}
